POST http://localhost:3000/addTodo
Content-Type: application/json

{
    "Name":"learn go",
}
### 
GET http://localhost:3000/getAllTodos

###
PUT http://localhost:3000/updateTodo/13
Content-Type: application/json

{
    "Name":"learn go 20",
    "IsDone": false
}